### PR TITLE
Add `smbmap` pypi package

### LINKED ISSUE #48: Make a pypi package
@ShawnDEvans, it would help people and maintainers if you could package `smbmap` in a standard Python package that could be available on pypi.org.

Take a look at my simple packages, like [`nmaptocsv`](https://pypi.org/project/nmaptocsv), it's quite easy :)

### PR DESCRIPTION
**Pull request by alichtman**
I created https://pypi.org/project/smbmap/ (which should fix #48).

I couldn't find your account on pypi. If you comment your username, I can add you as a maintainer.

The following works on my machine™:

```
$ sudo pip3 install smbmap
$ smbmap
```

### CODE REVIEW

**Comment by ShawnDEvans** [comment]
Could you add IdiotCoderMonkey as a maintainer in PyPi? I finally have some time to take a stab at figuring out PyPi publishing. Thanks!!

**Comment by alichtman** [comment]
image

Invited. You should enable 2FA on your account (if it's not already done).

**Comment by ShawnDEvans** [comment]
Hey Aaron,

Happy Thanksgiving! I hope you've been well. I finally revisited the PyPi
invitation and to no surprise it has expired. I made enough updates to the
GitHub repo it wouldn't hurt to update PyPi. Thanks man!

Best,
Shawn

**Comment by alichtman** [comment]
Sent you another invite! Cheers

**Comment by alichtman** [comment]
Quick reminder to set up 2FA!

**Comment by ShawnDEvans** [comment]
Done and done, thanks a bunch!

**Pull request merged**
